### ISSUE TITLE
rescue nil swallowing exceptions

### ISSUE THREAD

**Issue by midhunkrishna** [breamware/sidekiq-batch#13]
https://github.com/breamware/sidekiq-batch/blob/master/lib/sidekiq/batch/callback.rb#L12  swallows all exceptions. 

Ideally, this shouldn't be rescued, there by giving feedback to the developer

**Comment by infinite-monkeys** [comment]
We ran into this too. It was confusing as to why things failed.

**Comment by managr** [comment]
Released `0.1.4` with it (https://rubygems.org/gems/sidekiq-batch/versions/0.1.4) so closing.
