### ISSUE TITLE
String#constantize

### ISSUE THREAD

**Issue by kmatrah** [breamware/sidekiq-batch#15]
Hi! Nice gem! 

I came across a little problem when using callbacks. `Sidekiq::Batch::Callback::Worker#perform` makes use of ActiveSupport `String#constantize` method. For non-Rails apps for which ActiveSupport is not embedded by default, it crashes. I solved the issue by providing my own version of `String#constantize`.

We can either add an explicit dependency to ActiveSupport or directly provide a version of `String#constantize`.

**Comment by robotmay** [comment]
Could be replaced with the use of:

```
Object.const_get("NameOfClass")
```

**Comment by managr** [comment]
Hi @kmatrah, can you create a pull request for that?

**Comment by managr** [comment]
It should be resolved in master

**Comment by managr** [comment]
Closing as it's fixed in `0.1.5`
