### ISSUE TITLE
Question about status on callbacks

### ISSUE THREAD

**Issue by PedroSena** [breamware/sidekiq-batch#17]
Hi,

I'm starting with sidekiq-batch and I'd like to know if the result I'm getting is really expected/intended:

Whenever I finish a job batch when I see the status object that I receive both on on_success and on_complete I see they always have empty values when everything works as it should.
`{:total=>0, :failures=>0, :pending=>0, :created_at=>nil, :complete=>false, :failure_info=>[], :parent_bid=>nil}`
This is one example from a Batch that had a single job that was executed successfully. I was expecting to see total 1 and complete true but that didn't happen.

Whenever I have a batch containing one job that failed I see the info correctly set though.

Is this really intended ? Because I was expecting to be able to log such information on database upon completion but apparently I can't rely on this object I receive on the callback.

Thanks

**Comment by Jay-Plumb** [comment]
@PedroSena are you on sidekiq `5.x.x`? I have noticed issues with this gem with regards to the callbacks when upgrading from sidekiq `4.x.x` to `5.x.x`.

**Comment by PedroSena** [comment]
@Jay-Plumb Yes, Ruby 2.3.4 and Rails 5.1.4.
Good to know I'm not the only one, thanks Jay

**Comment by djgould** [comment]
I'm having this issue as well. Although it's seems intended (the redis keys are explicity being deleted up on success). I'm not sure if this is the best idea. I'd like to know what happened during a batch after it is completed. Any thoughts?

**Comment by EddFigueiredo** [comment]
I just started to use this gem,  and i'm having the same behavior here.
I'm on sidekip `4.2.0` rails `4.2.11` and ruby `2.3.6`
