### ISSUE TITLE
Extend batch expire time

### ISSUE THREAD

**Issue by maatz** [breamware/sidekiq-batch#18]
The issue:
We have batches that have a lot of (throttled) jobs, therefore a batch can take several days to complete. What we saw with those batches is, that callbacks are not executed.

What I think the reason is:
As far as I can see the callback is stored in `"BID-#{batch_id}-callback-complete"`, which is expiring after 30 **hours** (https://github.com/breamware/sidekiq-batch/blob/1e92bc2749e5b30ea44544bbab8dad5eb6d7558e/lib/sidekiq/batch.rb#L13), whereas Sidekiq Pro Batch uses 30 **days** (https://github.com/mperham/sidekiq/wiki/Batches#expiration).

Currently we just override it with `Sidekiq::Batch::BID_EXPIRE_TTL = 604_800`. Is it possible to either increase the default value to match Sidekiq pros setting, or even make it configurable?

Thanks!

**Comment by managr** [comment]
Hey @maatz 
Why do you override it to `604_800`? Shouldn't it be:
```ruby
irb(main):002:0> 3600 * 24 * 30
=> 2592000
```

**Comment by managr** [comment]
@maatz please do comment in:
https://github.com/breamware/sidekiq-batch/pull/19
