### ISSUE TITLE
Parameterize BID_EXPIRE_TTL to make it variable.

### ISSUE THREAD

**Issue by ohsawa0515** [breamware/sidekiq-batch#22]
Redis memory usage is squeezing as BID_EXPIRE_TTL has been extended to `2_592_000` with v0.1.5 change.

https://github.com/breamware/sidekiq-batch/compare/v0.1.4...v0.1.5

We strongly desire be able to make it variable according to our use case.

**Comment by ndbroadbent** [comment]
Thanks for opening this issue @ohsawa0515! Can you please give some more details about the memory usage that you are seeing? If you fork the gem and change `BID_EXPIRE_TTL` back to `108_000`, what memory usage do you see in that case? And also it would be helpful to know how many jobs you are processing within this 30 day window.

I am not a maintainer, but I've just found this gem and have started using it in production. It's really good to know that I should keep an eye on my Redis memory usage over the next 30 days, so thanks for that.

**Comment by managr** [comment]
@ohsawa0515 could you elaborate a bit. Since bumping `BID_EXPIRE_TTL` should not really bump the memory usage since anyway the keys are removed when the batch is finished.
The only reason to increase it was to allow long-running batches to complete correctly.
