### ISSUE TITLE
Skips on_success callback for some batches

### ISSUE THREAD

**Issue by rudrakshi2014** [breamware/sidekiq-batch#42]
While running multiple batches simultaneously, `on_success` callback is being skipped for few batches.
In sidekiq logs, there are no logs saying `DEBUG: Finalize success batch id:` for the respective batches. 
No issue noticed with `on_complete` callback.

**Comment by rudrakshi2014** [comment]
It is similar issue as of:
https://github.com/breamware/sidekiq-batch/issues/32#issue-481324048

It is marked as closed but yet not resolved.

**Comment by scootklein** [comment]
also been facing this issue recently. unable to find reproducible situation

**Comment by davidrichey** [comment]
Was this only happening when a job succeeded after a failure (a retried job)? I added a PR (#43) that addresses #32 from what I saw happening.

**Comment by rudrakshi2014** [comment]
Jobs were not failing but yet on_success calls were missing. The pattern I noticed was, these jobs are of same worker class.
Thanks @davidrichey for adding the fix for https://github.com/breamware/sidekiq-batch/issues/32#issue-481324048

**Comment by davidrichey** [comment]
Interesting. We have around ~1300 batches running a day and haven't seen this yet. Only errors we had we when a job failed, retried & succeeded and the on_success callback wouldn't run
