### ISSUE TITLE
`cleanup_redis` should not be called immediately after batch finishes

### ISSUE THREAD

**Issue by drj17** [breamware/sidekiq-batch#58]
Relates to #17 

It seems like when batches complete they call `cleanup_redis`, which removes all useful batch information from the store.  This prevents you from seeing the number of failed jobs, whether the job was complete, etc.  Is there a reason to do this immediately?

**Comment by nglx** [comment]
Well, not really I believe. Only a matter of not having junk in the Redis store. I think we might leave it for sometime.

**Comment by drj17** [comment]
> Well, not really I believe. Only a matter of not having junk in the Redis store. I think we might leave it for sometime.

As far as I can tell, this logic happens immediately on completion.  Commenting out the method fixes the issue for me, and I can view job data after completion.
