### ISSUE TITLE
Deprecations in logs

### ISSUE THREAD

**Issue by Mikkko** [breamware/sidekiq-batch#59]
After sidekiq update to 4.5.5, there is deprecation in console.
`Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /usr/share/rvm/gems/ruby-2.7.6/gems/sidekiq-batch-0.1.8/lib/sidekiq/batch.rb:46:in block (2 levels) in on').`
As I see, it is new problem and Sidekiq already merged PR with 4.5.6, that fixes their deprecations, but there is something from sidekiq-batch.

**Comment by ignaciovillaverde** [comment]
@Mikkko https://github.com/breamware/sidekiq-batch/pull/60 should fix it.
