### ISSUE TITLE
Callback success fired too soon with ActionMailer

### ISSUE THREAD

**Issue by KalaTheMother** [breamware/sidekiq-batch#67]
Hi,

The success callback is called too soon due to ActionMailer. (class ApplicationMailer < ActionMailer::Base)

I have a complex workflow with six steps (to start).
And when a mail is sent by ActionMailer in the middle of step 2, it fires success callback even the step 2 is not finished.

So, the step 3 begins whereas the step 2 is still in progress.

When I disable the sent of mail, the workflow is followed perfectly.

**Comment by aleksclark** [comment]
@KalaTheMother I believe #69 will actually fix this behavior
