### ISSUE TITLE
Job never gets set to complete and stats get deleted

### ISSUE THREAD

**Issue by barnaclebarnes** [breamware/sidekiq-batch#68]
I've added a batch of jobs:

```
batch = Sidekiq::Batch.new
batch.on(:success, Publishing::Status)
batch.jobs do
  # enqueue jobs
end
```

But as it progresses and I check the status I get this:

``` 
# Just started
batch_status = Sidekiq::Batch::Status.new(batch.bid)
batch_status.data => {:bid=>"D9u_HoEX5AAA7A", :total=>37, :failures=>0, :pending=>37, :created_at=>"1670976746.5037887", :complete=>false, :failure_info=>[], :parent_bid=>nil, :child_count=>0}}
# Part wy through
batch_status = Sidekiq::Batch::Status.new(batch.bid)
batch_status.data => {:bid=>"D9u_HoEX5AAA7A", :total=>37, :failures=>0, :pending=>21, :created_at=>"1670976746.5037887", :complete=>false, :failure_info=>[], :parent_bid=>nil, :child_count=>0}}
# Completed (no errors)
batch_status = Sidekiq::Batch::Status.new(batch.bid)
batch_status.data => {:bid=>"D9u_HoEX5AAA7A", :total=>0, :failures=>0, :pending=>0, :created_at=>nil, :complete=>false, :failure_info=>[], :parent_bid=>nil, :child_count=>0}}
```

It seems that after the last batch finishes, it wipes out the counts and never sets the `complete` flag to `true`.

Any ideas of what could be going on here?

**Comment by aleksclark** [comment]
@barnaclebarnes haven't looked into this specifically, but #69 does some related things, you might try it and see if it helps.

**Comment by Allerby** [comment]
Can confirm that I'm seeing the same issue as @barnaclebarnes, unfortunately @aleksclark's PR doesn't seem to resolve it.

**Comment by bilouw** [comment]
Hi !

I have the same issue ! Don't understand how people use this gem if the base feature (batch status) is broken.
Does the official sidekiq pro gem also have this bug ?

**Comment by aleksclark** [comment]
@Allerby @bilouw @barnaclebarnes Happy to take a gander at this now that I've got some familiarity with the internals. Can you provide a code sample for repro? There are some redis things that could make this happen but we use this gem 24/7 so I'm surprised it's completely broken (that said we mostly rely on the callbacks, not manually grabbing status from Redis)

**Comment by bilouw** [comment]
I'm using a very simple code. Here a pseudo code sample:

`batch = Sidekiq::Batch.new
  batch.description = "Batch #{batch.bid} started "
  batch.on(:success, MyCallback)

  batch.jobs do
    some_loop do
      someJob.perform_async
    end
  end
`

Have you tried to fetch the batch status like we do ? (you mentioned that you mostly rely on callback).
Maybe you simply never noticed that !

**Comment by simonc** [comment]
Hi there. I'm facing the same issue as sometimes the Finalize callback will erase the batch stats before it can be used. From what I understand the Sidekiq Pro version simply lets the data be expired and does not actually clean anything explicitly but I might be wrong.

The only workaround I found at the moment is to simply monkey-patch in an initializer

```ruby
# config/initializers/sidekiq_batch.rb

class Sidekiq::Batch
  def self.cleanup_redis(bid)
    # Monkey-patch to prevent agressive batch stats cleanup
    # see https://github.com/breamware/sidekiq-batch/issues/68
  end
end
```
