### ISSUE TITLE
0.1.9 still incompatible with redis-client which is used by Sidekiq 7 

### ISSUE THREAD

**Issue by JosephTico** [breamware/sidekiq-batch#87]
The issue #66 is still happening, this was not fixed, but for some reason was marked as closed. The latest version of sidekiq-batch is not compatible with Sidekiq 7.

**Comment by nglx** [comment]
This should be addressed in #89

**Comment by dsandstrom** [comment]
Is it possible to get a new gem release? Thank you.

**Comment by tianlu1677** [comment]
Please make a new release for this mr
