### ISSUE TITLE
Sidekiq 7 compatibility

### ISSUE THREAD

**Issue by damuz91** [breamware/sidekiq-batch#91]
Even tho it seems guys have managed to make it to work with Sidekiq 7, the gem in the latest version does not seem to have included this changes. 

Therefore, I used the ref to the [commit](https://github.com/breamware/sidekiq-batch/commit/f2ef0289ea23e652797741de96506957535099ff) where all the fixes where pushed and now I got sidekiq-batch working with Sidekiq 7.

```
gem 'sidekiq-batch', git: 'git@github.com:breamware/sidekiq-batch.git', ref: 'f2ef0289ea23e652797741de96506957535099ff'
```

I see this [related issue](https://github.com/breamware/sidekiq-batch/issues/87), but it's been closed.

Please release a new version, and off course, thanks for a great gem!

**Comment by dsandstrom** [comment]
@nglx Thanks for the gem and merging the fix, but is it possible to release a new gem version? 

Does anyone else have rubygems access?

**Comment by ayemane** [comment]
That fixed my problem!
I have been getting this error soon as batch.jobs block finishes executing
"Unsupported command argument type: Array"
Thank you

> Even tho it seems guys have managed to make it to work with Sidekiq 7, the gem in the latest version does not seem to have included this changes.
> 
> Therefore, I used the ref to the [commit](https://github.com/breamware/sidekiq-batch/commit/f2ef0289ea23e652797741de96506957535099ff) where all the fixes where pushed and now I got sidekiq-batch working with Sidekiq 7.
> 
> ```
> gem 'sidekiq-batch', git: 'git@github.com:breamware/sidekiq-batch.git', ref: 'f2ef0289ea23e652797741de96506957535099ff'
> ```
> 
> I see this [related issue](https://github.com/breamware/sidekiq-batch/issues/87), but it's been closed.
> 
> Please release a new version, and off course, thanks for a great gem!

**Comment by hebbo** [comment]
Hey there team! Any news about publishing the latest change?

Is the fix stable in production for those who are using it? Thanks!

**Comment by nglx** [comment]
Apologies for late response.
The new version is release now:
https://rubygems.org/gems/sidekiq-batch/versions/0.2.0

Thanks for all the input ❤️
